### ISSUE TITLE
Task for Valerie

### ISSUE THREAD

**Issue by Katierichard** [Wiredcraft/interview#5]
Thank you for taking the time to interview with us. We'd like to assign you the following tasks to test the way you think and how you work with our team.

Please complete the following - 
1. Critique our marketing material (blog posts, case studies, and social media - twitter/Linkedin/Weibo/Wechat) 
2. Set some goals for a Weibo Strategy and create a 5-step plan to show how you'd implement them
3. Write a Weibo post in Chinese to advertise for the [Sales and Business Development position](https://wiredcraft.com/jobs/sales-business-development/)

Please do the above tasks in this [Hackpad](https://hackpad.com/Task-for-Valerie-r3KB9CnIvQl). Hackpad allows for teams to collaborate on a document, track editing and automatically save edits.

If you have any questions, feel free to contact me on GitHub or on Slack.

Overly communicating is never a problem.

**Comment by valerielol** [comment]
Thanks Katie, will start work on that! :)

**Comment by valerielol** [comment]
Hi @Katierichard , finished my tasks on Hackpad.
Any suggestions or comments please let me know!
Best,
Valerie
